package com.kara4k.popupblocker.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kara4k.popupblocker.model.Package;

import com.kara4k.popupblocker.model.PackageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig packageDaoConfig;

    private final PackageDao packageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        packageDaoConfig = daoConfigMap.get(PackageDao.class).clone();
        packageDaoConfig.initIdentityScope(type);

        packageDao = new PackageDao(packageDaoConfig, this);

        registerDao(Package.class, packageDao);
    }
    
    public void clear() {
        packageDaoConfig.clearIdentityScope();
    }

    public PackageDao getPackageDao() {
        return packageDao;
    }

}
