package com.kara4k.popupblocker.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kara4k.popupblocker.model.Package;
import com.kara4k.popupblocker.model.Rule;

import com.kara4k.popupblocker.model.PackageDao;
import com.kara4k.popupblocker.model.RuleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig packageDaoConfig;
    private final DaoConfig ruleDaoConfig;

    private final PackageDao packageDao;
    private final RuleDao ruleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        packageDaoConfig = daoConfigMap.get(PackageDao.class).clone();
        packageDaoConfig.initIdentityScope(type);

        ruleDaoConfig = daoConfigMap.get(RuleDao.class).clone();
        ruleDaoConfig.initIdentityScope(type);

        packageDao = new PackageDao(packageDaoConfig, this);
        ruleDao = new RuleDao(ruleDaoConfig, this);

        registerDao(Package.class, packageDao);
        registerDao(Rule.class, ruleDao);
    }
    
    public void clear() {
        packageDaoConfig.clearIdentityScope();
        ruleDaoConfig.clearIdentityScope();
    }

    public PackageDao getPackageDao() {
        return packageDao;
    }

    public RuleDao getRuleDao() {
        return ruleDao;
    }

}
