package com.kara4k.popupblocker.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kara4k.popupblocker.model.Package;
import com.kara4k.popupblocker.model.Word;

import com.kara4k.popupblocker.model.PackageDao;
import com.kara4k.popupblocker.model.WordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig packageDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final PackageDao packageDao;
    private final WordDao wordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        packageDaoConfig = daoConfigMap.get(PackageDao.class).clone();
        packageDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        packageDao = new PackageDao(packageDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(Package.class, packageDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        packageDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
    }

    public PackageDao getPackageDao() {
        return packageDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
